#!/bin/bash

## declare an array variable
declare -a arr=( animation CMakeLists.txt enemy game gameState gameStateMachine health hero inputHandler jsonLoader main playState position projectile sprite structs target textures vector dataLevel1.json dataMain.json )

arr=( animation CMakeLists.txt enemy game health hero inputHandler jsonLoader main playState position projectile sprite structs target textures vector dataLevel1.json dataMain.json edit )

if [ $HOSTNAME == "archbox" ]
then
  syscall="gedit "
else
  syscall="xed "
fi

for i in "${arr[@]}"
do
   #echo "$i"
   if [ -e "$i.hpp" ]; then
     syscall+="$i.hpp "
   fi
   
   if [ -e "$i.cpp" ]; then
     syscall+="$i.cpp "
   fi
   
   if [ -e "$i" ]; then
     if [ $i != game ]; then
       syscall+="$i "
     fi
   fi
   
   if [ -e "assets/$i" ]; then
     syscall+="assets/$i "
   fi
   
   
done

echo $syscall
eval $syscall &

exit 0

